name: lzma
version: 0.4.0+2
author: Juan Mellado <jcmellado@gmail.com>
homepage: https://github.com/jcmellado/dart-lzma
description: LZMA compression library.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
    fixnum: ^1.0.0
  
dev_dependencies:
  test: ^1.3.0
