name: lzma
version: 0.4.0+2
author: Juan Mellado <jcmellado@gmail.com>
homepage: https://github.com/jcmellado/dart-lzma
description: LZMA compression library.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ">=0.9.0 <0.11.0"
  
dev_dependencies:
  test: ^1.3.0
